name: Compilar Cliente Vortek Custom

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar Código Fuente
        uses: actions/checkout@v4

      - name: Instalar Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Configurar e Instalar NDK r26b Puro de Google
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b
          link-to-sdk: true

      - name: Configurar y Compilar Proyecto con CMake
        run: |
          # Declaramos la ruta absoluta de instalación del r26b directamente en el comando para saltarnos el bloqueo
          cmake -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=/usr/local/lib/android/sdk/ndk/26.1.10909125/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-24 \
            -DCMAKE_BUILD_TYPE=Release \
            -B build
          
          ninja -C build

      - name: Guardar Binarios Compilados (.so)
        uses: actions/upload-artifact@v4
        with:
          name: vortek-driver-mali-custom
          path: |
            build/*.so
            vortek_icd.aarch64.json
