name: Compilar Cliente Vortek Custom

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar Código Fuente
        uses: actions/checkout@v4

      - name: Instalar Ninja y Herramientas
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build wget unzip

      - name: Descargar de forma Automática todos los Archivos y Cabeceras Faltantes
        run: |
          # 1. Creamos la carpeta para las cabeceras nativas de Vulkan de Android
          mkdir -p include/vulkan
          
          # 2. Descargamos las cabeceras ICD usando el dominio RAW correcto de GitHub
          wget https://githubusercontent.com -O include/vulkan/vk_icd.h
          wget https://githubusercontent.com -O include/vulkan/vk_layer.h
          
          # 3. Descargamos el núcleo de Vulkan v1.3.268 para dar soporte nativo a MapMemoryPlaced y divisores
          wget https://githubusercontent.com -O include/vulkan/vulkan_core.h

      - name: Configurar e Instalar NDK r26b Oficial de Google
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b
          link-to-sdk: true

      - name: Configurar y Compilar Proyecto con CMake
        run: |
          cmake -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=/usr/local/lib/android/sdk/ndk/26.1.10909125/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-24 \
            -DCMAKE_BUILD_TYPE=Release \
            -B build
          
          ninja -C build

      - name: Guardar Binarios Compilados (.so)
        uses: actions/upload-artifact@v4
        with:
          name: vortek-driver-mali-custom
          path: |
            build/*.so
            vortek_icd.aarch64.json
