name: Compilar Cliente Vortek Custom

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar Código Fuente de Vortek
        uses: actions/checkout@v4

      - name: Instalar Ninja y Herramientas
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Clonar de forma Nativa las Cabeceras Oficiales de Vulkan Faltantes
        run: |
          # 1. Creamos las carpetas estructuradas que pide el núcleo de Vulkan
          mkdir -p include/vulkan
          mkdir -p include/vk_video
          
          # 2. Clonamos de forma temporal el repositorio oficial completo de Khronos
          git clone --depth 1 -b v1.3.268 https://github.com khronos_headers
          
          # 3. Copiamos los archivos base de Vulkan y las carpetas de códecs de video necesarias
          cp khronos_headers/include/vulkan/*.h include/vulkan/
          cp khronos_headers/include/vk_video/*.h include/vk_video/
          
          # 4. Limpiamos la carpeta temporal
          rm -rf khronos_headers

      - name: Configurar e Instalar NDK r26b Oficial de Google
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b
          link-to-sdk: true

      - name: Configurar y Compilar Proyecto con CMake
        run: |
          cmake -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=/usr/local/lib/android/sdk/ndk/26.1.10909125/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-24 \
            -DCMAKE_BUILD_TYPE=Release \
            -B build
          
          ninja -C build

      - name: Guardar Binarios Compilados (.so)
        uses: actions/upload-artifact@v4
        with:
          name: vortek-driver-mali-custom
          path: |
            build/*.so
            vortek_icd.aarch64.json
